// Generated by scripts/gen-tour-strings.py from tours.json. Don't edit;
// rerun the script after changing tours.json.

#include "Tours.h"

#include <QtGlobal>

namespace bld::ui::tours {

namespace {

const char* const kStrings[] = {
    QT_TRANSLATE_NOOP("Tours", "Welcome to Brick Layout Designer"),
    QT_TRANSLATE_NOOP("Tours", "Plan a LEGO layout for your next show, on your own or with your club."),
    QT_TRANSLATE_NOOP("Tours", "Start or open a layout"),
    QT_TRANSLATE_NOOP("Tours", "Begin with an empty map, or open a file from this app or BlueBrick."),
    QT_TRANSLATE_NOOP("Tours", "Join a club"),
    QT_TRANSLATE_NOOP("Tours", "Share layouts, venues and parts with the people you build with."),
    QT_TRANSLATE_NOOP("Tours", "Take the tour"),
    QT_TRANSLATE_NOOP("Tours", "A few short steps that show you the main buttons."),
    QT_TRANSLATE_NOOP("Tours", "Not now"),
    QT_TRANSLATE_NOOP("Tours", "Next"),
    QT_TRANSLATE_NOOP("Tours", "Back"),
    QT_TRANSLATE_NOOP("Tours", "Skip"),
    QT_TRANSLATE_NOOP("Tours", "Done"),
    QT_TRANSLATE_NOOP("Tours", "{n} of {total}"),
    QT_TRANSLATE_NOOP("Tours", "The editor"),
    QT_TRANSLATE_NOOP("Tours", "All your pieces live here"),
    QT_TRANSLATE_NOOP("Tours", "Search by name, or pick a group like Train track. Drag a piece onto the map to place it."),
    QT_TRANSLATE_NOOP("Tours", "Sheets"),
    QT_TRANSLATE_NOOP("Tours", "A layout is built on sheets, like see-through pages. Hide one to see what is under it."),
    QT_TRANSLATE_NOOP("Tours", "Place and move"),
    QT_TRANSLATE_NOOP("Tours", "Click a piece to pick it, then drag it to move it. Drag a box around pieces to pick several."),
    QT_TRANSLATE_NOOP("Tours", "Bend flexible track"),
    QT_TRANSLATE_NOOP("Tours", "Pick a flexible track, then drag the round handle at its free end to bend it."),
    QT_TRANSLATE_NOOP("Tours", "Saving and live sync"),
    QT_TRANSLATE_NOOP("Tours", "This shows whether your changes are saved. In a shared layout, everyone's changes appear live."),
    QT_TRANSLATE_NOOP("Tours", "Share a picture"),
    QT_TRANSLATE_NOOP("Tours", "Make a picture of your layout to post, print or send to your club."),
    QT_TRANSLATE_NOOP("Tours", "Help is always here"),
    QT_TRANSLATE_NOOP("Tours", "Click a ? for a quick tip. The Help menu has the other tours and all help topics."),
    QT_TRANSLATE_NOOP("Tours", "Venues"),
    QT_TRANSLATE_NOOP("Tours", "Draw your venue"),
    QT_TRANSLATE_NOOP("Tours", "Draw the walls first, then add doors, openings and things in the way, like pillars."),
    QT_TRANSLATE_NOOP("Tours", "Real sizes"),
    QT_TRANSLATE_NOOP("Tours", "Type sizes in feet and inches or metres. The app works out the studs for you."),
    QT_TRANSLATE_NOOP("Tours", "Straight walls"),
    QT_TRANSLATE_NOOP("Tours", "Snap keeps walls straight and corners square while you draw."),
    QT_TRANSLATE_NOOP("Tours", "Trace a floor plan"),
    QT_TRANSLATE_NOOP("Tours", "Have a plan of the hall? Put the picture underneath and draw over it."),
    QT_TRANSLATE_NOOP("Tours", "Save the venue"),
    QT_TRANSLATE_NOOP("Tours", "Save it, and start new layouts from it whenever you show there."),
    QT_TRANSLATE_NOOP("Tours", "Clubs"),
    QT_TRANSLATE_NOOP("Tours", "Your server"),
    QT_TRANSLATE_NOOP("Tours", "This shows whether you are connected to your club's server. Click it to add a server or sign in."),
    QT_TRANSLATE_NOOP("Tours", "Mine and my clubs'"),
    QT_TRANSLATE_NOOP("Tours", "Pick All, Mine or a club to see just those layouts, venues and parts."),
    QT_TRANSLATE_NOOP("Tours", "Save to"),
    QT_TRANSLATE_NOOP("Tours", "When you make or publish a layout, Save to picks whether it is yours or your club's."),
    QT_TRANSLATE_NOOP("Tours", "Your club's page"),
    QT_TRANSLATE_NOOP("Tours", "The club page shows who is in the club. Admins invite people from there."),
    QT_TRANSLATE_NOOP("Tours", "Joining a club"),
    QT_TRANSLATE_NOOP("Tours", "A club admin sends you an invite link. Open it to join, and the club's things show up here."),
    QT_TRANSLATE_NOOP("Tours", "Looking at a layout"),
    QT_TRANSLATE_NOOP("Tours", "Look around"),
    QT_TRANSLATE_NOOP("Tours", "Drag with one finger to move around. Pinch to zoom in and out."),
    QT_TRANSLATE_NOOP("Tours", "Make changes"),
    QT_TRANSLATE_NOOP("Tours", "Tap Edit to change the layout, if you are allowed to. Tap a piece to pick it, then drag it to move it."),
    QT_TRANSLATE_NOOP("Tours", "Saved views"),
    QT_TRANSLATE_NOOP("Tours", "Tap the layout's name to jump to a saved view, or to see the whole layout."),
    QT_TRANSLATE_NOOP("Tours", "Make a picture of the layout to send to friends."),
    QT_TRANSLATE_NOOP("Tours", "Tap ? for tips, and to take the other tours."),
};

}  // namespace

QStringList tourStrings() {
    QStringList out;
    for (const char* s : kStrings) out << QString::fromUtf8(s);
    return out;
}

}  // namespace bld::ui::tours
