#!/usr/bin/env python3
"""Writes src/ui/tours/TourStrings.cpp from src/ui/tours/tours.json.

tours.json is shared word for word with the web app, so its text can't
carry tr() calls. This lists every string people read in it, marked with
QT_TRANSLATE_NOOP("Tours", ...), so lupdate puts them in the .ts files;
the app translates them when it reads the file (Tours.cpp). Run it after
changing tours.json; ToursTest checks the two match.
"""
import json
import pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
TOURS = ROOT / "src/ui/tours/tours.json"
OUT = ROOT / "src/ui/tours/TourStrings.cpp"


def strings(doc):
    w = doc["welcome"]
    yield w["title"]
    yield w["text"]
    for key in ("layout", "club", "tour"):
        yield w["actions"][key]["label"]
        yield w["actions"][key]["text"]
    yield w["dismiss"]
    for key in ("next", "back", "skip", "done", "of"):
        yield doc["buttons"][key]
    for t in doc["tours"]:
        yield t["title"]
        for s in t["steps"]:
            yield s["title"]
            yield s["text"]


def c_string(s):
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def main():
    seen = []
    for s in strings(json.loads(TOURS.read_text(encoding="utf-8"))):
        if s not in seen:
            seen.append(s)
    lines = [
        "// Generated by scripts/gen-tour-strings.py from tours.json. Don't edit;",
        "// rerun the script after changing tours.json.",
        "",
        '#include "Tours.h"',
        "",
        "#include <QtGlobal>",
        "",
        "namespace bld::ui::tours {",
        "",
        "namespace {",
        "",
        "const char* const kStrings[] = {",
    ]
    lines += [f'    QT_TRANSLATE_NOOP("Tours", {c_string(s)}),' for s in seen]
    lines += [
        "};",
        "",
        "}  // namespace",
        "",
        "QStringList tourStrings() {",
        "    QStringList out;",
        "    for (const char* s : kStrings) out << QString::fromUtf8(s);",
        "    return out;",
        "}",
        "",
        "}  // namespace bld::ui::tours",
        "",
    ]
    OUT.write_text("\n".join(lines), encoding="utf-8")


if __name__ == "__main__":
    main()
